### ISSUE TITLE
Unable to show OP location

### ISSUE THREAD

**Issue by MrVideo** [jamesafk/TabLocation#7]
Hi, I found your plugin recently and it works for standard players, but apparently it doesn't for OPs. I tried looking for commands or a setting in the config file but had no luck. How do I show OP coordinates without deopping myself or the others?

**Comment by jamesafk** [comment]
There might be an issue with the permission. I will look into it but it worked fine in my testing. If you have a permissions plugin for now you could try going into that and removing the permission "tablocation.hide" from you or all the ops. Also, what Minecraft version are you on?

**Comment by jamesafk** [comment]
It has been 3 days and I cannot replicate the issue so I am closing this issue. If it is experienced again please open a new issue.
